PLTcode/config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :path_prefix => 'plt', :controllers => { :registrations => "registrations" }
  resources :users
  resources :installations do
    resources :sites
  end
  resources :sites do
    resources :volunteers
    resources :contributors
  end
  resources :languages do
    resources :articles
  end
  resources :articles

   root 'welcome#index'
   get '*unmatched_route', :to => 'welcome#index'

end

PLTcode/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
        user ||= User.new # guest user (not logged in)
	if user.role == 'Admin'
	   can :manage, :all
	elsif user.role == 'Volunteer'
	   can [:read, :update], Site
	   can :read, [Language, User]
	   can :manage, [Contributor, Article]
	elsif user.role == 'Contributor'
	   can [:read, :create, :update], Article
	end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

PLTcode/app/models/article.rb
class Article < ActiveRecord::Base
 default_scope -> { order('created_at DESC') }
 belongs_to :language
 mount_uploader :picture, PictureUploader
end

PLTcode/app/models/contributor.rb
class Contributor < ActiveRecord::Base
  belongs_to :site
  validates :name, presence: true
end

PLTcode/app/models/installation.rb
class Installation < ActiveRecord::Base
 has_many :sites , dependent: :destroy
 validates :installation, presence: true
end

PLTcode/app/models/language.rb
class Language < ActiveRecord::Base
 has_many :articles, dependent: :destroy
 validates :name, presence: true
end

PLTcode/app/models/site.rb
class Site < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  belongs_to :installation
  has_many :volunteers , dependent: :destroy
  has_many :contributors , dependent: :destroy
  validates :name, presence: true
end

PLTcode/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  default_scope -> { order('created_at DESC') }
  validates_uniqueness_of :username
  validates_confirmation_of :password, length: { in: 6..20 }
  validates_presence_of :username, :role, :login_approval, :first_name, :last_name
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
end

PLTcode/app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  belongs_to :site
  validates :vname, presence: true
end

PLTcode/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 load_and_authorize_resource

 def new
  @article = Article.new
 end

 def index
   @articles = Article.where("id > ? and created_at > ?", params[:article_id].to_i, Time.at(params[:after].to_i ) + 1 )
 end

 def create
  @article = Article.new(article_params)
 
  if @article.save
   redirect_to @article
  else
   render 'new'
  end
 end

 def edit
  @article = Article.find(params[:id])
 end

 def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
 end

 def show
  @article = Article.find(params[:id])
 end

 def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
 end
 
 private
  def article_params
    params.require(:article).permit(:category, :english, :phonetic, :picture, :language_id)
  end
end

PLTcode/app/controllers/installations_controller.rb
class InstallationsController < ApplicationController
 load_and_authorize_resource

 def new
   @installation = Installation.new
 end

 def edit
   @installation = Installation.find(params[:id])
 end

 def index
   @installations = Installation.all
 end

 def show
   @installation = Installation.find(params[:id])
 end

 def destroy
  @installation = Installation.find(params[:id])
  @installation.destroy
 
  redirect_to installations_path
 end

 def update
   @installation = Installation.find(params[:id])
 
  if @installation.update(installation_params)
        redirect_to @installation
  else
    render 'edit'
  end
 end

 def create
     @installation = Installation.new(installation_params)
	 
     if @installation.save
        redirect_to @installation
     else
        render 'new'
     end
 end

 private
   def installation_params
       params.require(:installation).permit(:installation, :email, :address, :contact)
   end
end

PLTcode/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
 load_and_authorize_resource

 def new
   @language = Language.new
 end

 def index
  @languages = Language.all
 end

 def create
  @language = Language.new(language_params)
 
  if @language.save
   redirect_to @language
  else
   render 'new'
  end
 end

 def edit
  @language = Language.find(params[:id])
 end

 def destroy
  @language = Language.find(params[:id])
  @language.destroy
 
  redirect_to languages_path
 end

 def show
  @language = Language.find(params[:id])
 end

 def update
  @language = Language.find(params[:id])
 
  if @language.update(language_params)
    redirect_to @language
  else
    render 'edit'
  end
 end
 
 private
  def language_params
    params.require(:language).permit(:name)
  end

end

PLTcode/app/controllers/sites_controller.rb
class SitesController < ApplicationController
 load_and_authorize_resource

 def new
  @site = Site.new
 end

 def index
  @sites = Site.all
 end

 def create
  @site = Site.new(site_params)
 
  if @site.save
   redirect_to @site
  else
   render 'new'
  end
 end

 def edit
  @site = Site.find(params[:id])
 end

 def destroy
  @site = Site.find(params[:id])
  @site.destroy
 
  redirect_to sites_path
 end

 def show
  @site = Site.find(params[:id])
 end

 def update
  @site = Site.find(params[:id])
 
  if @site.update(site_params)
    redirect_to @site
  else
    render 'edit'
  end
 end
 
 private
  def site_params
    params.require(:site).permit(:name, :installation_id)
  end

end

PLTcode/app/controllers/users_controller.rb
class UsersController < ApplicationController
 load_and_authorize_resource

 def new
  @user = User.new
 end

 def index
  @users = User.all
 end

 def create
  @user = User.new(user_params)
 
  if @user.save
   redirect_to @user
  else
   render 'new'
  end
 end

 def edit
  @user = User.find(params[:id])
 end

 def destroy
  @user = User.find(params[:id])
  @user.destroy
 
  redirect_to users_path
 end

 def show
  @user = User.find(params[:id])
 end

 def update
  @user = User.find(params[:id])
 
  if @user.update(user_params)
    redirect_to @user
  else
    render 'edit'
  end
 end
 
 private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :location, :lang, :contact, :gender, :role, :login_approval)
  end

end

PLTcode/app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  load_and_authorize_resource

  def create
     @site = Site.find(params[:site_id])
     @volunteer = @site.volunteers.create(volunteer_params)
     redirect_to site_path(@site)
  end

  def destroy
     @site = Site.find(params[:site_id])
     @volunteer = @site.volunteers.find(params[:id])
     @volunteer.destroy
     redirect_to site_path(@site)
  end

  private
    def volunteer_params
      params.require(:volunteer).permit(:vname)
    end
end

PLTcode/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

PLTcode/app/helpers/application_helper.rb
module ApplicationHelper
end

PLTcode/app/helpers/articles_helper.rb
module ArticlesHelper
end

PLTcode/app/helpers/contributors_helper.rb
module ContributorsHelper
end

PLTcode/app/helpers/installations_helper.rb
module InstallationsHelper
end

PLTcode/app/helpers/languages_helper.rb
module LanguagesHelper
end

PLTcode/app/helpers/sites_helper.rb
module SitesHelper
end

PLTcode/app/helpers/volunteers_helper.rb
module VolunteersHelper
end

PLTcode/app/helpers/welcome_helper.rb
module WelcomeHelper
end

PLTcode/app/views/installations/_form.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<%= form_for @installation do |f| %>
  <% if @installation.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@installation.errors.count, "error") %> prohibited this post contact information from being saved:</h2>
	     <ul>
		 <% @installation.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
	         <% end %>
	     </ul>
     </div>
   <% end %>
  <p>
    <%= f.label :Post %><br>
    <%= f.text_field :installation %>
  </p>

  <p>
    <%= f.label :Email_Id %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :Address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.label :Contact_Number %><br>
    <%= f.text_field :contact %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<% end %>
<% end %>

PLTcode/app/views/installations/edit.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<h1>Editing post contact information</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', installations_path %>
<% end %>
<% end %>

PLTcode/app/views/installations/index.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<h1>Listing posts</h1>
<p><u><b><%= link_to '+New post', new_installation_path %></b></u></p>

<table id="customers">
  <tr>
     <th>Post</th>
     <th>Email Id</th>
     <th>Address</th>
     <th>Contact Number</th>
    <th colspan="3"></th>
  </tr>

<% @installations.each do |installation| %>
  <tr>
     <td><%= installation.installation %></td>
     <td><%= installation.email %></td>
     <td><%= installation.address %></td>
     <td><%= installation.contact %></td>
      <td><%= link_to 'Show', installation_path(installation) %></td>
      <td><%= link_to 'Edit', edit_installation_path(installation) %></td>
      <td><%= link_to 'Delete', installation_path(installation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

</table>
<hr/>
<% end %>
<% end %>

PLTcode/app/views/installations/new.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<h1>New post contact information</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', installations_path %>
<% end %>
<% end %>

PLTcode/app/views/installations/show.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<h1>Saved post contact information</h1>
<p>
  <strong>Post:</strong>
  <%= @installation.installation %>
</p>
<p>
  <strong>Email Id:</strong>
  <%= @installation.email %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @installation.address %>
</p>
 
<p>
  <strong>Contact Number:</strong>
  <%= @installation.contact %>
</p>

<p><strong>Sites:</strong><ol>
<% @installation.sites.each do |site| %>
  <li>
          <%= site.name %>
  </li>	     
<% end %></ol></p>

<%= link_to 'Back', installations_path %>
<%= link_to 'Edit', edit_installation_path(@installation) %>
<% end %>
<% end %>