PLTcode/config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :path_prefix => 'plt', :controllers => { :registrations => "registrations" }
  resources :users
  resources :installations do
    resources :sites
  end
  resources :sites do
    resources :volunteers
    resources :contributors
  end
  resources :languages do
    resources :articles
  end
  resources :articles

   root 'welcome#index'
   get '*unmatched_route', :to => 'welcome#index'

end

PLTcode/app/models/language.rb
class Language < ActiveRecord::Base
 has_many :articles, dependent: :destroy
 validates :name, presence: true
end

PLTcode/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
 load_and_authorize_resource

 def new
   @language = Language.new
 end

 def index
  @languages = Language.all
 end

 def create
  @language = Language.new(language_params)
 
  if @language.save
   redirect_to @language
  else
   render 'new'
  end
 end

 def edit
  @language = Language.find(params[:id])
 end

 def destroy
  @language = Language.find(params[:id])
  @language.destroy
 
  redirect_to languages_path
 end

 def show
  @language = Language.find(params[:id])
 end

 def update
  @language = Language.find(params[:id])
 
  if @language.update(language_params)
    redirect_to @language
  else
    render 'edit'
  end
 end
 
 private
  def language_params
    params.require(:language).permit(:name)
  end

end

PLTcode/app/helpers/languages_helper.rb
module LanguagesHelper
end

PLTcode/app/views/languages/_form.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<%= form_for @language do |f| %>
  <% if @language.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@language.errors.count, "error") %> prohibited
      this language from being saved:</h2>
    <ul>
    <% @language.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<% end %>
<% end %>

PLTcode/app/views/languages/edit.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<h1>Editing language</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', languages_path %>
  <% end %>
<% end %>

PLTcode/app/views/languages/index.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' or current_user.role == 'Volunteer' or current_user.role == 'Contributor' %>
<h1>Listing Languages</h1>
<% if current_user.role == 'Admin' %>
<p><u><b><%= link_to '+New language', new_language_path %></b></u></p>
<% end %>
 
<table id="customers">
  <tr>
    <th>Name</th>
<% if current_user.role == 'Admin' %>
    <th colspan="3"></th>
<% else %>
    <th colspan="1"></th>
<% end %>
  </tr>
  <% @languages.each do |language| %>
    <tr>
      <td><%= language.name %></td>
      <td><%= link_to 'Photos', language_path(language) %></td>
<% if current_user.role == 'Admin' %>
      <td><%= link_to 'Edit', edit_language_path(language) %></td>
      <td><%= link_to 'Delete', language_path(language), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
    </tr>
  <% end %>
</table>
<hr/>
  <% end %>
  <% end %>

PLTcode/app/views/languages/new.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<h1>New language</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', languages_path %>
<% end %>
<% end %>

PLTcode/app/views/languages/show.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' or current_user.role == 'Volunteer' or current_user.role == 'Contributor' %>
<h1>Photos under <%= @language.name %> language </h1>
<br/>
<ol>
<% @language.articles.each do |article| %><li>
<p>
  <strong>Category:</strong>
  <%= article.category %>
</p>
<p>
  <strong>English Text:</strong>
  <%= article.english %>
</p> 
<p>
  <strong>Phonetic Text:</strong>
  <%= article.phonetic %>
</p>
<p>
  <strong>Picture:</strong>
  <%= image_tag(article.picture_url, :width => 600) if article.picture.present? %>
</p>
<% end %></ol>

<%= link_to 'Back', languages_path %>
<% end %>
<% end %>