PLTcode/config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :path_prefix => 'plt', :controllers => { :registrations => "registrations" }
  resources :users
  resources :installations do
    resources :sites
  end
  resources :sites do
    resources :volunteers
    resources :contributors
  end
  resources :languages do
    resources :articles
  end
  resources :articles

   root 'welcome#index'
   get '*unmatched_route', :to => 'welcome#index'

end

PLTcode/app/models/site.rb
class Site < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  belongs_to :installation
  has_many :volunteers , dependent: :destroy
  has_many :contributors , dependent: :destroy
  validates :name, presence: true
end

PLTcode/app/controllers/sites_controller.rb
class SitesController < ApplicationController
 load_and_authorize_resource

 def new
  @site = Site.new
 end

 def index
  @sites = Site.all
 end

 def create
  @site = Site.new(site_params)
 
  if @site.save
   redirect_to @site
  else
   render 'new'
  end
 end

 def edit
  @site = Site.find(params[:id])
 end

 def destroy
  @site = Site.find(params[:id])
  @site.destroy
 
  redirect_to sites_path
 end

 def show
  @site = Site.find(params[:id])
 end

 def update
  @site = Site.find(params[:id])
 
  if @site.update(site_params)
    redirect_to @site
  else
    render 'edit'
  end
 end
 
 private
  def site_params
    params.require(:site).permit(:name, :installation_id)
  end

end

PLTcode/app/helpers/sites_helper.rb
module SitesHelper
end

PLTcode/app/views/sites/_form.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' or current_user.role == 'Volunteer' %>
<%= form_for @site do |f| %>
  <% if @site.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@site.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @site.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :Post %><br>
    <%= f.collection_select(:installation_id, Installation.all, :id, :installation) %>
  </p>
  <p>
    <%= f.label :Site %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<% end %>
<% end %>

PLTcode/app/views/sites/edit.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' or current_user.role == 'Volunteer' %>
<h1>Editing site</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', sites_path %>
<% end %>
<% end %>

PLTcode/app/views/sites/index.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' or current_user.role == 'Volunteer' %>
<h1>Listing sites</h1>
<% if current_user.role == 'Admin' %>
<p><u><b><%= link_to '+New site', new_site_path %></b></u></p>
<% end %>
 
<!-- table class="reference" style="width:45%; border:5; cellpadding:4; cellspacing:3" -->
<table id="customers">
  <tr>
    <th>Post</th>
    <th>Site</th>
<% if current_user.role == 'Admin' %>
    <th colspan="3"></th>
<% else %>
    <th colspan="2"></th>
<% end %>
  </tr>
 
  <% @sites.each do |site| %>
    <tr>
      <td><%= site.installation.installation %></td>
      <td><%= site.name %></td>
      <td><%= link_to 'Show', site_path(site) %></td>
      <td><%= link_to 'Edit', edit_site_path(site) %></td>
<% if current_user.role == 'Admin' %>
      <td><%= link_to 'Delete', site_path(site), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
    </tr>
  <% end %>
</table>
<hr/>
<% end %>
<% end %>

PLTcode/app/views/sites/new.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' %>
<h1>New site</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', sites_path %>
<% end %>
<% end %>

PLTcode/app/views/sites/show.html.erb
<% if current_user.login_approval == 'Yes' %>
<% if current_user.role == 'Admin' or current_user.role == 'Volunteer' %>
<h1>Saved site information</h1>
<p>
  <strong>Post:</strong>
  <%= @site.installation.installation %>
</p>
<p>
  <strong>Site name:</strong>
  <%= @site.name %>
</p>
<p><strong>Volunteers:</strong><ol>
<% @site.volunteers.each do |volunteer| %>
  <li>
          <%= volunteer.vname %>&nbsp;
<% if current_user.role == 'Admin' %>
	  <%= link_to 'Delete', [volunteer.site, volunteer], method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
  </li>	     
<% end %></ol></p>

<% if current_user.role == 'Admin' %>
<h2>Add a volunteer name:</h2>
<%= form_for([@site, @site.volunteers.build]) do |f| %>
  <% if @site.volunteers.build.errors.any? %>
  <% end %>
   <p>
	<%= f.label :Volunteer_Name %><br>
	<%= f.text_field :vname %>
   </p>
   <p>
	<%= f.submit %>
   </p>
<% end %>
<% end %>

<p><strong>Contributors:</strong><ol>
<% @site.contributors.each do |contributor| %>
  <li>
          <%= contributor.name %>&nbsp;<%= link_to 'Delete', [contributor.site, contributor], method: :delete, data: { confirm: 'Are you sure?' } %>
  </li>	     
<% end %></ol></p>

<h2>Add a contributor name:</h2>
<%= form_for([@site, @site.contributors.build]) do |f| %>
  <% if @site.contributors.build.errors.any? %>
  <% end %>
   <p>
	<%= f.label :Contributor_Name %><br>
	<%= f.text_field :name %>
   </p>
   <p>
	<%= f.submit %>
   </p>
<% end %>
<%= link_to 'Back', sites_path %>
<%= link_to 'Edit', edit_site_path(@site) %>
<% end %>
<% end %>